---
- name: Полная настройка FreeIPA (Сервер + Пользователи + Группы)
  hosts: all
  become: true

  vars:
    # Настройки сервера
    ipaadmin_password: "MySecretPassword123"
    ipadm_password: "DirectoryManagerPass123"
    ipaserver_domain: "lab.local"
    ipaserver_realm: "LAB.LOCAL"
    ipaserver_setup_dns: yes
    ipaserver_forwarders: ["8.8.8.8"]

  roles:
    - role: freeipa.ansible_freeipa.ipaserver
      state: present

  tasks:
    - name: Создание тестовой группы "devs"
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: devs
        description: "Группа разработчиков"

    - name: Создание тестового пользователя "student1"
      freeipa.ansible_freeipa.ipauser:
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: student1
        first: Ivan
        last: Ivanov
        password: "StudentPassword123!"
        update_password: on_force_change # Потребует смену пароля при первом входе
        group: devs
